version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

  bot:
    build:
      context: ./bot
    ports:
      - "3002:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: