services:
  - type: web
    name: accord-frontend
    env: docker
    buildCommand: docker build -t accord-frontend ./accord-platform/frontend
    envVars:
      - key: VITE_API_URL
        value: https://accord-backend.onrender.com

  - type: web
    name: accord-backend
    env: docker
    buildCommand: docker build -t accord-backend ./accord-platform/backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: accord-db
          property: connectionString

  - type: worker
    name: accord-bot
    env: docker
    buildCommand: docker build -t accord-bot ./accord-platform/bot
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false

databases:
  - name: accord-db
    databaseName: accord
    ipAllowList: []